"""Serialize a validated `OKFBundle` to a conformant OKF v0.1 directory bundle.

OKF v0.1 (GoogleCloudPlatform/knowledge-catalog) is a directory of Markdown
files with YAML frontmatter. Layout we emit:

    index.md              -- bundle root: `okf_version` + a listing of concepts
    log.md                -- dated update history (reserved file)
    tables/<name>.md      -- one concept per table: frontmatter + `# Schema` table

Conformance (§8 of the spec): every non-reserved file has parseable YAML
frontmatter with a non-empty `type`. Our `confidence` / source-of-truth signals
are carried as producer-defined extension keys (`okf_x_*`) and an extra Schema
column, which the spec explicitly permits ("Producers MAY include any
additional keys"; consumers MUST preserve unknown keys).
"""

from __future__ import annotations

import io
import re
import zipfile
from datetime import datetime, timezone

import yaml

from okf_weaver.models import OKFBundle, OKFColumn, OKFTable


def bundle_to_files(bundle: OKFBundle) -> dict[str, str]:
    """Render the bundle to a ``{path: text}`` mapping (an OKF directory)."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    files: dict[str, str] = {
        "index.md": _index(bundle),
        "log.md": _log(len(bundle.tables), ts[:10]),
    }
    for table in bundle.tables:
        files[f"tables/{table.name}.md"] = _table_file(table, ts)
    return files


def serialize_bundle(bundle: OKFBundle) -> bytes:
    """Render the bundle and pack the OKF directory into a `.zip` archive."""
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for path, content in bundle_to_files(bundle).items():
            archive.writestr(path, content)
    return buffer.getvalue()


def bundle_filename(bundle: OKFBundle) -> str:
    """Derive a safe `.zip` download name from the bundle's name (ASCII slug)."""
    slug = re.sub(r"[^a-z0-9]+", "-", bundle.name.lower()).strip("-")
    return f"{slug or 'okf-bundle'}.zip"


def _index(bundle: OKFBundle) -> str:
    # Bundle-root index.md — the one place okf_version is declared (spec §5).
    frontmatter = yaml.safe_dump(
        {"okf_version": bundle.okf_version, "name": bundle.name}, sort_keys=False
    ).strip()
    lines = [f"# {bundle.name}", "", "Generated by OKF Weaver.", "", "# Tables", ""]
    for table in bundle.tables:
        lines.append(f"* [{table.name}](/tables/{table.name}.md) - {_one_line(table.description)}")
    return f"---\n{frontmatter}\n---\n\n" + "\n".join(lines) + "\n"


def _log(n: int, date: str) -> str:
    plural = "" if n == 1 else "s"
    return (
        "# Directory Update Log\n\n"
        f"## {date}\n"
        f"* **Generation**: Created OKF bundle with {n} table{plural} via OKF Weaver.\n"
    )


def _table_file(table: OKFTable, timestamp: str) -> str:
    frontmatter = yaml.safe_dump(
        {
            "type": "Table",  # REQUIRED by OKF; types are not centrally registered
            "title": table.name,
            "description": _one_line(table.description),
            "timestamp": timestamp,
            "okf_x_source_of_truth": table.is_source_of_truth,
            "okf_x_table_confidence": round(table.confidence, 2),
        },
        sort_keys=False,
    ).strip()

    rows = [
        "# Schema",
        "",
        "| Column | Type | Description | Confidence |",
        "|---|---|---|---|",
    ]
    for column in table.columns:
        rows.append(
            f"| `{column.name}` | {column.data_type} | {_description_cell(column)} "
            f"| {column.confidence:.2f} |"
        )
    return f"---\n{frontmatter}\n---\n\n" + "\n".join(rows) + "\n"


def _description_cell(column: OKFColumn) -> str:
    facts = []
    if column.is_primary_key:
        facts.append("Primary key.")
    if not column.nullable:
        facts.append("Not null.")
    text = _escape_cell(column.definition)
    if column.references:
        ref_table = column.references.split(".", 1)[0]
        text = f"{text} FK to [{ref_table}](/tables/{ref_table}.md)."
    return (" ".join(facts) + " " + text).strip()


def _one_line(text: str) -> str:
    return " ".join(text.split())


def _escape_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()
